import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useRef,useState } from "react";
import { Alert,Modal,Pressable,StyleSheet,Text,View } from "react-native";
import { Screen,ScrollFadeItem } from "../../src/components/Screen";
import { radii,spacing,typography } from "../../src/design/tokens";
import { mostRecentIncomplete } from "../../src/documents/insights";
import { useDocumentLibrary } from "../../src/documents/DocumentLibraryProvider";
import { useVoticTheme } from "../../src/theme/ThemeProvider";
import { HomeEmptyAnimation } from "../../src/components/EmptyStateIllustrations";
import { useDocumentTransition } from "../../src/navigation/DocumentTransitionProvider";
import { DocumentTypeIcon } from "../../src/components/DocumentTypeIcon";

export default function Home(){
  const {theme}=useVoticTheme(); const {documents,collections,openDocument,setDocumentCollection,removeDocument}=useDocumentLibrary();
  const transition=useDocumentTransition();
  const cardRefs=useRef<Record<string,View|null>>({});
  const [menuId,setMenuId]=useState<string|null>(null);
  const recent=mostRecentIncomplete(documents); const visible=documents.slice(0,3);
  const menuDocument=documents.find(document=>document.id===menuId);
  function open(id:string,sourceKey=id){
    const source=cardRefs.current[sourceKey];
    if(!source||transition.transitioning)return;
    source.measureInWindow((x,y,width,height)=>{openDocument(id);transition.openReader({x,y,width,height},()=>router.push("/reader"));});
  }
  function remove(){if(!menuDocument)return;const selected=menuDocument;setMenuId(null);Alert.alert("Delete document?",`Remove ${selected.title} from Votic? This cannot be undone.`,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>removeDocument(selected.id)}]);}
  return <Screen title="Home" hideTitle>
    <ScrollFadeItem><View style={[s.hero,{backgroundColor:theme.surfaceMuted}]}><View style={s.heroCopy}><Text style={[s.welcome,{color:theme.mutedText}]}>Welcome back</Text><Text style={[s.heroTitle,{color:theme.text}]}>Ready to read?</Text><Text style={[s.heroBody,{color:theme.mutedText}]}>Upload a document or pick up where you left off.</Text></View><View style={[s.heroArt,{backgroundColor:theme.sentenceHighlight}]}><Ionicons name="document-text" size={44} color={theme.accent}/></View><Pressable onPress={()=>router.push("/documents")} style={[s.upload,{backgroundColor:theme.accent}]}><Ionicons name="add" size={22} color="#FFF"/><Text style={s.uploadText}>Upload Document</Text></Pressable></View></ScrollFadeItem>
    <SectionHeader title="Continue Reading" onPress={()=>router.push("/documents")}/>
    {recent?<ScrollFadeItem><Pressable ref={node=>{cardRefs.current["recent:"+recent.id]=node;}} collapsable={false} onPress={()=>open(recent.id,"recent:"+recent.id)} style={({pressed})=>[s.continueCard,{backgroundColor:theme.surface,borderColor:theme.border,opacity:pressed?.82:1}]}><DocumentTypeIcon sourceName={recent.sourceName}/><View style={s.flex}><Text numberOfLines={1} style={[s.docTitle,{color:theme.text}]}>{recent.title}</Text><Text style={[s.meta,{color:theme.mutedText}]}>{recent.sentenceIndex+1} passages · {Math.round(recent.progress*100)}% read</Text><View style={[s.track,{backgroundColor:theme.border}]}><View style={[s.progress,{backgroundColor:theme.accent,width:`${recent.progress*100}%` as `${number}%`}]}/></View></View><View style={[s.play,{backgroundColor:theme.accent}]}><Ionicons name="play" size={20} color="#FFF"/></View></Pressable></ScrollFadeItem>:<Pressable accessibilityRole="button" accessibilityLabel="Choose your first document" onPress={()=>router.push("/documents")} style={[s.homeEmpty,{borderColor:theme.border}]}><HomeEmptyAnimation/><Text style={[s.emptyText,{color:theme.text}]}>Choose your first document</Text></Pressable>}
    <SectionHeader title="My Documents" onPress={()=>router.push("/documents")}/>
    <View style={[s.documentList,{backgroundColor:theme.surface,borderColor:theme.border}]}>{visible.length?visible.map((doc,i)=><ScrollFadeItem key={doc.id}><View ref={node=>{cardRefs.current[doc.id]=node;}} collapsable={false} style={[s.documentRow,i<visible.length-1&&{borderBottomColor:theme.border,borderBottomWidth:1}]}><Pressable accessibilityRole="button" accessibilityLabel={`Open ${doc.title}`} onPress={()=>open(doc.id)} style={({pressed})=>[s.documentMain,{opacity:pressed?.82:1,backgroundColor:pressed?theme.surfaceMuted:"transparent"}]}><DocumentTypeIcon sourceName={doc.sourceName}/><View style={s.flex}><Text numberOfLines={1} style={[s.docTitle,{color:theme.text}]}>{doc.title}</Text><Text style={[s.meta,{color:theme.mutedText}]}>{doc.progress?`${Math.round(doc.progress*100)}% read`:"Ready to read"}</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`More options for ${doc.title}`} onPress={()=>setMenuId(doc.id)} style={s.moreButton}><Ionicons name="ellipsis-horizontal" size={21} color={theme.mutedText}/></Pressable></View></ScrollFadeItem>):<Text style={[s.noDocs,{color:theme.mutedText}]}>Your recent documents will appear here.</Text>}</View>
    <Text style={[s.sectionTitle,{color:theme.text}]}>Quick Actions</Text><View style={s.quickRow}><QuickAction icon="book-outline" label="Reader" caption="Read and listen" color="#4F46E5" onPress={()=>recent?open(recent.id):router.push("/documents")}/><QuickAction icon="chatbubble-ellipses-outline" label="Ask Votic" caption="Get answers" color="#2563EB" onPress={()=>router.push("/ask")}/><QuickAction icon="document-text-outline" label="Notes" caption="View your notes" color="#D97706" onPress={()=>router.push("/notes")}/></View>
    <Modal visible={menuId!==null} transparent animationType="fade" onRequestClose={()=>setMenuId(null)}><Pressable onPress={()=>setMenuId(null)} style={s.backdrop}><Pressable onPress={event=>event.stopPropagation()} style={[s.menu,{backgroundColor:theme.surface}]}><View style={s.menuHeader}><View style={s.flex}><Text style={[s.menuTitle,{color:theme.text}]}>Document options</Text><Text numberOfLines={1} style={[s.menuSubtitle,{color:theme.mutedText}]}>{menuDocument?.title}</Text></View><Pressable onPress={()=>setMenuId(null)} style={s.close}><Ionicons name="close" size={22} color={theme.text}/></Pressable></View><MenuAction icon="book-outline" label="Open in Reader" onPress={()=>{if(menuId)open(menuId);setMenuId(null);}}/><Text style={[s.moveLabel,{color:theme.mutedText}]}>MOVE TO</Text><MenuAction icon="folder-outline" label="Unfiled" selected={!menuDocument?.collection} onPress={()=>{if(menuId)setDocumentCollection(menuId);setMenuId(null);}}/>{collections.map(collection=><MenuAction key={collection} icon="folder-outline" label={collection} selected={menuDocument?.collection===collection} onPress={()=>{if(menuId)setDocumentCollection(menuId,collection);setMenuId(null);}}/>)}<MenuAction icon="trash-outline" label="Delete document" destructive onPress={remove}/></Pressable></Pressable></Modal>
  </Screen>;
}
function SectionHeader({title,onPress}:{title:string;onPress:()=>void}){const {theme}=useVoticTheme();return <View style={s.sectionHeader}><Text style={[s.sectionTitle,{color:theme.text}]}>{title}</Text><Pressable onPress={onPress}><Text style={[s.action,{color:theme.accent}]}>See All</Text></Pressable></View>;}
function QuickAction({icon,label,caption,color,onPress}:{icon:React.ComponentProps<typeof Ionicons>["name"];label:string;caption:string;color:string;onPress:()=>void}){const {theme}=useVoticTheme();return <Pressable onPress={onPress} style={[s.quick,{backgroundColor:color+(theme.isDark?"24":"10")}]}><Ionicons name={icon} size={30} color={color}/><Text style={[s.quickLabel,{color:theme.isDark?"#FFF":theme.text}]}>{label}</Text><Text style={[s.quickCaption,{color:theme.mutedText}]}>{caption}</Text></Pressable>;}
function MenuAction({icon,label,onPress,selected=false,destructive=false}:{icon:React.ComponentProps<typeof Ionicons>["name"];label:string;onPress:()=>void;selected?:boolean;destructive?:boolean}){const {theme}=useVoticTheme();const color=destructive?"#DC2626":theme.text;return <Pressable onPress={onPress} style={({pressed})=>[s.menuAction,{backgroundColor:pressed?theme.surfaceMuted:"transparent"}]}><Ionicons name={icon} size={21} color={color}/><Text style={[s.menuActionText,{color}]}>{label}</Text>{selected?<Ionicons name="checkmark" size={20} color={theme.accent}/>:null}</Pressable>;}
const s=StyleSheet.create({homeEmpty:{minHeight:260,borderWidth:1,borderRadius:radii.lg,alignItems:"center",justifyContent:"center",paddingBottom:spacing.md},hero:{borderRadius:radii.lg,padding:spacing.lg,flexDirection:"row",flexWrap:"wrap",gap:spacing.md},heroCopy:{flex:1,minWidth:190},welcome:{fontSize:13},heroTitle:{fontSize:25,fontWeight:"900",letterSpacing:-.6,marginTop:2},heroBody:{fontSize:14,lineHeight:20,marginTop:4},heroArt:{width:64,height:72,borderRadius:14,alignItems:"center",justifyContent:"center",transform:[{rotate:"-4deg"}]},upload:{width:"100%",minHeight:48,borderRadius:12,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},uploadText:{color:"#FFF",fontSize:16,fontWeight:"800"},sectionHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:4},sectionTitle:{...typography.sectionTitle,fontSize:18},action:{fontSize:13,fontWeight:"800"},continueCard:{minHeight:82,borderWidth:1,borderRadius:radii.md,padding:10,flexDirection:"row",alignItems:"center",gap:12},emptyCard:{minHeight:72,borderWidth:1,borderRadius:radii.md,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10},emptyText:{fontWeight:"700"},docIcon:{width:46,height:46,borderRadius:10,alignItems:"center",justifyContent:"center"},flex:{flex:1},docTitle:{fontSize:14,fontWeight:"800"},meta:{fontSize:12,marginTop:4},track:{height:4,borderRadius:2,overflow:"hidden",marginTop:8},progress:{height:"100%"},play:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center"},documentList:{borderWidth:1,borderRadius:radii.md,overflow:"hidden"},documentRow:{minHeight:70,flexDirection:"row",alignItems:"stretch"},documentMain:{flex:1,padding:10,flexDirection:"row",alignItems:"center",gap:12},moreButton:{width:52,alignItems:"center",justifyContent:"center"},noDocs:{padding:20,textAlign:"center",fontSize:14},quickRow:{flexDirection:"row",gap:8},quick:{flex:1,minHeight:112,borderRadius:14,padding:10,alignItems:"center",justifyContent:"center"},quickLabel:{fontSize:13,fontWeight:"800",color:"#111827",marginTop:7,textAlign:"center"},quickCaption:{fontSize:10,color:"#6B7280",marginTop:2,textAlign:"center"},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.38)",justifyContent:"center",padding:24},menu:{borderRadius:20,padding:16,gap:2},menuHeader:{flexDirection:"row",alignItems:"center",marginBottom:8},menuTitle:{fontSize:20,fontWeight:"800"},menuSubtitle:{fontSize:13,marginTop:2},close:{width:44,height:44,alignItems:"center",justifyContent:"center"},moveLabel:{fontSize:11,fontWeight:"800",letterSpacing:.7,marginTop:10,marginBottom:2},menuAction:{minHeight:50,borderRadius:12,paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:12},menuActionText:{fontSize:15,fontWeight:"700",flex:1}});
